# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a5d36dde56e614492d75e0e19619eff19885b996b2fc1ef4f595686839bfaebb3d6ad7f9e81686acae74c75a0811b731ba1db173f78ece0f072f2ca574c6102

test:
  secret_key_base: 96c8f986f2666e8f1d9639c45cf1620da4702fac962de546d826f60d3c7d063a59a7907427bb7389e9c28c8e2cc1d59ab40a2f2ed94187ec99f2c9daa15b9eff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
